"""Shell completion scripts generated from the argparse tree.

Generating them means a new command or flag is completable automatically;
hand-written scripts drifted from the real CLI.
"""

from __future__ import annotations

import argparse
from typing import Dict, List, Tuple

Spec = Dict[str, Tuple[str, List[str], List[str]]]  # command -> (help, options, subcommands)


def _subparsers(parser: argparse.ArgumentParser):
    for action in parser._actions:  # noqa: SLF001 - argparse has no public API for this
        if isinstance(action, argparse._SubParsersAction):  # noqa: SLF001
            return action
    return None


def _options(parser: argparse.ArgumentParser) -> List[str]:
    return [
        opt
        for action in parser._actions  # noqa: SLF001
        if action.help != argparse.SUPPRESS
        for opt in action.option_strings
        if opt.startswith("--")
    ]


def spec(parser: argparse.ArgumentParser) -> Spec:
    sub = _subparsers(parser)
    helps = {a.dest: a.help or "" for a in sub._choices_actions}  # noqa: SLF001
    result: Spec = {}
    for name, child in sub.choices.items():
        nested = _subparsers(child)
        words = (
            list(nested.choices)
            if nested
            else [
                str(choice)
                for action in child._actions  # noqa: SLF001
                if not action.option_strings and action.choices
                for choice in action.choices
            ]
        )
        result[name] = (helps.get(name, ""), _options(child), words)
    return result


def bash(s: Spec) -> str:
    cases = []
    for name, (_, opts, subs) in s.items():
        words = " ".join(opts)
        if subs:
            cases.append(
                f'        {name}) if [[ $COMP_CWORD -eq 2 ]]; then words="{" ".join(subs)}"; '
                f'else words="{words}"; fi ;;'
            )
        else:
            cases.append(f'        {name}) words="{words}" ;;')
    return "\n".join(
        [
            "# bash completion for apsta (generated by `apsta completion bash`)",
            "_apsta() {",
            '    local cur="${COMP_WORDS[COMP_CWORD]}" words=""',
            "    if [[ $COMP_CWORD -eq 1 ]]; then",
            f'        COMPREPLY=( $(compgen -W "{" ".join(s)}" -- "$cur") ); return 0',
            "    fi",
            '    case "${COMP_WORDS[1]}" in',
            *cases,
            "    esac",
            '    COMPREPLY=( $(compgen -W "$words" -- "$cur") )',
            "}",
            "complete -F _apsta apsta",
        ]
    )


def zsh(s: Spec) -> str:
    described = "\n".join(f"        '{n}:{h.replace(chr(39), '')}'" for n, (h, _, _) in s.items())
    cases = []
    for name, (_, opts, subs) in s.items():
        if subs:
            first, rest = " ".join(subs), " ".join(opts)
            cases.append(f"        {name}) (( CURRENT == 2 )) && compadd -- {first} || compadd -- {rest} ;;")
        elif opts:
            cases.append(f"        {name}) compadd -- {' '.join(opts)} ;;")
    return "\n".join(
        [
            "#compdef apsta",
            "# zsh completion for apsta (generated by `apsta completion zsh`)",
            "_apsta() {",
            "    local -a commands",
            "    commands=(",
            described,
            "    )",
            "    if (( CURRENT == 2 )); then",
            "        _describe 'command' commands; return",
            "    fi",
            "    shift words; (( CURRENT-- ))",
            "    case $words[1] in",
            *cases,
            "    esac",
            "}",
            '_apsta "$@"',
        ]
    )


def fish(s: Spec) -> str:
    lines = ["# fish completion for apsta (generated by `apsta completion fish`)", "complete -c apsta -f"]
    for name, (help_text, opts, subs) in s.items():
        lines.append(f'complete -c apsta -n "__fish_use_subcommand" -a "{name}" -d "{help_text}"')
        if subs:
            lines.append(f'complete -c apsta -n "__fish_seen_subcommand_from {name}" -a "{" ".join(subs)}"')
        for opt in opts:
            lines.append(f'complete -c apsta -n "__fish_seen_subcommand_from {name}" -l {opt[2:]}')
    return "\n".join(lines)


GENERATORS = {"bash": bash, "zsh": zsh, "fish": fish}


def cmd_completion(args) -> int:
    print(GENERATORS[args.shell](spec(args.parser)))
    return 0
